### PR TITLE
fix(dashboard): add dynamic user search

### LINKED ISSUE #1009: [BUG] Non-Dynamic search in member dashboard page
Description:
> There's a bug in add member dashboard page. We want to fetch user list as a person types the username. Right now it just fetches the list once and searched within the list.

cc: @harshtandiya

### PR DESCRIPTION
**Pull request by HarshPatel5940**
This pull request fixes the user search within the member dashboard page.

### Frontend Enhancements:
* Updated `AddMember.vue` to replace static member options with dynamic search results using the new `search_user_profiles` API. Added UI feedback for loading states and empty search results. [[1]](diffhunk://#diff-be16afcd2dfb767b18a3a75eb39db75b336c29774c0afce518996cf72e8b293fL14-R44) [[2]](diffhunk://#diff-be16afcd2dfb767b18a3a75eb39db75b336c29774c0afce518996cf72e8b293fL63-R108)
* Introduced new reactive properties (`searchTerm`, `searchResults`, `isSearching`) and methods (`handleSearchInput`, `handleClearSearch`) to manage search functionality and debounce API calls. [[1]](diffhunk://#diff-be16afcd2dfb767b18a3a75eb39db75b336c29774c0afce518996cf72e8b293fL85-L105) [[2]](diffhunk://#diff-be16afcd2dfb767b18a3a75eb39db75b336c29774c0afce518996cf72e8b293fR162-R221)
* Ensured proper cleanup of resources by clearing timeouts on component unmount.

### Backend Support:
* Added `search_user_profiles` API in `dashboard.py` to enable real-time user search with filters for existing members and partial matches on username or full name.

---

fixes: https://github.com/fossunited/fossunited/issues/1009

## Summary by CodeRabbit

- New Features
  - Improved “Add Member” autocomplete: debounced search with loading state, safer option handling, descriptive labels, error message on load failure, and Add button disabled while loading or when no new selection.
- Bug Fixes
  - Search requires a minimum query length (2+ chars) and returns a limited, filtered set of profiles.
- Style
  - Minor template and formatting cleanups across components.

### CODE REVIEW

File: dashboard/src/components/chapter/AddMember.vue [hunk 1]
```diff
@@ -11,12 +11,37 @@
...
+              <div v-if="searchTerm && searchTerm.length < 2">
+                Type at least 2 characters to search
+              </div>
+              <div
+                v-else-if="
+                  searchTerm && searchResults.length === 0 && !isSearching
+                "
+              >
+                No users found matching "{{ searchTerm }}"
+              </div>
```
Comment (harshtandiya) [inline dashboard/src/components/chapter/AddMember.vue]: Autocomplete has no such slot `#empty-state`

**Review by harshtandiya — COMMENTED** [review]
most of this is unnecessary code.

All that was needed to be done was to add a watcher to Autocomplete to watch as the profile usernames are types. On that change, we needed to pass the the search terms safely and return the results.

File: fossunited/api/dashboard.py [hunk 2]
```diff
@@ -178,3 +178,41 @@ def get_user_profile_list(filters: dict = None) -> list:
...
+    profiles = frappe.db.get_all(
+        USER_PROFILE,
+        filters=filters,
+        or_filters=or_filters,
+        fields=[
+            "full_name",
+            "profile_photo",
+            "route",
+            "username",
+            "name",
```
Comment (harshtandiya) [inline fossunited/api/dashboard.py]: never give out the name ID

Comment (HarshPatel5940) [reply fossunited/api/dashboard.py]: I don't get it. 🤔

**Comment by HarshPatel5940** [comment]
> All that was needed to be done was to add a watcher to Autocomplete to watch as the profile usernames are types. On that change, we needed to pass the the search terms safely and return the results.

Ah yes, thank you for pointing it out. I have updated the code to use an watcher as you suggested. 

you also said `never give out the name ID` - what do you mean, i dont understand? (i think its being returned now also)

File: fossunited/api/dashboard.py (hunk 2 above)
Comment (gi-yt) [reply fossunited/api/dashboard.py]: name id could also "leak" the names of anonymous users afaik

Comment (HarshPatel5940) [reply fossunited/api/dashboard.py]: @gi-yt hey, can you re-review ones the diff? it would be helpful.

**Comment by HarshPatel5940** [comment]
> never give out the name ID

 @gi-yt  @harshtandiya i did it based on referring this... and i checked browser console its already being fetched.  https://github.com/fossunited/fossunited/blob/3df21191fc51b2383c97e4127000429c840e0884/fossunited/api/dashboard.py#L175
 
 Also just realised. why is the name ids inside a field called "name"...  just curious.

**Review by harshtandiya — COMMENTED** [review]
did you test it out? Can you attach a screen recording of this?

**Comment by HarshPatel5940** [comment]
> did you test it out? Can you attach a screen recording of this?

Nope, was not able to test cause having issues which bench and sql 😢 ... I will get of some folks, resolve, test and send the screen recording once done.

**Comment by harshtandiya** [comment]
@HarshPatel5940 let me know if i can help

**Comment by HarshPatel5940** [comment]
> @HarshPatel5940 let me know if i can help

Mhm sure! By any chance you can test the changes?

**Comment by harshtandiya** [comment]
@coderabbitai review this

**Comment by harshtandiya** [comment]
Linters are failing, please take a look

**Comment by HarshPatel5940** [comment]
> Linters are failing, please take a look

Okay, boss will look into it.

**Comment by HarshPatel5940** [comment]
@harshtandiya formatted the code using prettier 👍🏼

**Comment by HarshPatel5940** [comment]
@coderabbitai review

**Comment by HarshPatel5940** [comment]
Hmm...

**Comment by HarshPatel5940** [comment]
+ @idlip

**Comment by idlip** [comment]
Hi @HarshPatel5940 
cc @rahulporuri 

LGTM.

TLDR; This PR makes dynamic search for user profiles while adding them to chapter/event members.
Kinda lazy loading, so we dont fetch full list of users.

- @HarshPatel5940 One suggestion to push.

Currently the search (frontend) only filters based on username, although we get `full_name` data from backend, we are not using it.

just update the `return. label` in AddMember.vue code to include `full_name` data as well.

File: dashboard/src/components/chapter/AddMember.vue [hunk 3]
```diff
@@ -78,27 +85,28 @@ const props = defineProps({
...
         name: ['not in', existingMembers.value],
       },
+      search_term: searchTerm.value,
     }
   },
-  auto: true,
-  realtime: true,
   transform(data) {
     return data.map((user) => {
       return {
```
Comment (idlip) [inline dashboard/src/components/chapter/AddMember.vue:118]: `label: `${user.full_name} (${user.username})`,`

Adding this enable us to search by full name as well. Since username is hit or a miss

Comment (HarshPatel5940) [reply dashboard/src/components/chapter/AddMember.vue:118]: Hmm okay.

Comment (HarshPatel5940) [reply dashboard/src/components/chapter/AddMember.vue:118]: resolved it in https://github.com/fossunited/fossunited/pull/1010/commits/868ba9b366404dbc84445e3e5f06c3288d2b4f9b

**Comment by idlip** [comment]
@HarshPatel5940 

Last one, Can you please check those ^ (9) nitpick comments by coderabbit (`🧹 Nitpick comments (9)`)
I think those are worth it to enhance.

let me what you think.

**Comment by HarshPatel5940** [comment]
yes, i think those nitpicks could be usefull. Let me implement those.

**Comment by HarshPatel5940** [comment]
I am unsure if changing deep to false will have significant effect, I don't have much experience with using deep in my very little vue life.

**Review by idlip — APPROVED** [review]

**Comment by idlip** [comment]
thanks!
