### PR TITLE
fix: allow '@' in URLs

### LINKED ISSUE #1014: Mastodon URLs are considered invalid because of `@`
Mastodon URLs contain a `@` character, which is considered invalid on the client side:

Image

As a workaround using `https://tatooine.club/%40nemo` seems to work, but this shouldn't be required.

### PR DESCRIPTION
**Pull request by gi-yt**
closes #1014

### CODE REVIEW

File: dashboard/src/pages/MyProfile.vue [hunk 1]
```diff
@@ -330,16 +330,15 @@ const toggleShowActivity = () => {
...
-    '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|' + // domain name
-    '((\\d{1,3}\\.){3}\\d{1,3}))' + // OR ip (v4) address
-    '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*' + // port and path
-    '(\\?[;&a-z\\d%_.~+=-]*)?' + // query string
-    '(\\#[-a-z\\d_]*)?$',
-  'i',
-) // fragment locator
+const isValidUrl = (url) => {
+  try {
+    isUrl = new URL(string);
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]: params is url but you are passing string

File: dashboard/src/pages/MyProfile.vue [hunk 2]
```diff
@@ -330,16 +330,15 @@ const toggleShowActivity = () => {
...
+  } catch (_) {
+    return false;
+  }
+
+  return url.protocol === "http:" || url.protocol === "https:";
+}
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]:
```js
try {
    const parsed = new URL(string);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }

File: dashboard/src/pages/MyProfile.vue [hunk 3]
```diff
@@ -361,7 +360,7 @@ const updateProfileErrors = () => {
   }
   Object.keys(socials).forEach((key) => {
     const url = socials[key]
-    if (url && !pattern.test(url)) {
+    if (url && isValidUrl(url)) {
       errors.push(`\n${key} is not a valid url`)
     }
   })
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]:
```js

  Object.entries(socials).forEach(([key, url]) => {
    if (url && !isValidUrl(url)) {
      errors.push(`${key} is not a valid URL`);
    }
  });
```

**Comment by harshtandiya** [comment]
Emphasizing for testing this for different kind of URLs, success and failure too

**Comment by gi-yt** [comment]
fixed, and tested

**Comment by harshtandiya** [comment]
Please add screenshots of error popping up / not popping up on 🙏🏽

**Comment by gi-yt** [comment]
image

**Comment by gi-yt** [comment]
image

**Review by harshtandiya — APPROVED** [review]
