### PR TITLE
fix: URL validation for profile saves (closes #916)

### LINKED ISSUE #916: [BUG] URL validation in edit profile triggering multiple toasts
### Describe the bug

The URL validation, when given a incorrect URL triggers multiple toasts showing the same error

### Expected behavior

It should only trigger a single error toast, and the HTML should be parsed correctly.

A good to have feature along this is to redirect to the profile page, after the edits are submitted

### To Reproduce

Profile > Edit > Type Incorrect URL in website field > 3 toasts appear

### Screenshots

https://github.com/user-attachments/assets/8691d822-5379-4d85-b897-f4edb208219b

### Environment

```markdown
- Device: Laptop (Macbook M4 Pro)
- OS: MacOS 15.3.2
- Browser: Zen (Firefox based)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gi-yt**
## What type of PR is this? (check all applicable)

- [ ] 🍕Feature
- [ ] ⚙️Chore
- [x] 🐛Bug Fix
- [ ] 🎨Style
- [ ] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description

Instead of sending the url validation back to frappe backend, I fix the problem by doing url validation on vuejs side itself

## Related Issues & Docs
closes #916 

## Checklist

- [X] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [X] I have tested these changes locally.
- [X] I have updated the documentation (If applicable).
- [X] The code follows the project's coding standards.
- [X] I have added/updated tests, if applicable.

### CODE REVIEW

**Comment by harshtandiya** [comment]
you need to install pre-commit and run it in your codebase. 

I suggest:
- install pre-commit
- reset your last commit in this branch
- run pre-commit
- force push again

**Comment by gi-yt** [comment]
its good for review now right?

File: dashboard/src/pages/MyProfile.vue [hunk 1]
```diff
@@ -280,11 +280,42 @@ const toggleProfilePrivacy = () => {
 
 const updateErrors = ref('')
 
+// Random Javascript regex to validate URLs
+// Source - https://stackoverflow.com/a/5717133 (yes i know copy paste is bad but im jsphobic)
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]: Hi, just the source comment should be fine here

File: dashboard/src/pages/MyProfile.vue [hunk 2]
```diff
@@ -280,11 +280,42 @@ const toggleProfilePrivacy = () => {
 
 const updateErrors = ref('')
 
+// Random Javascript regex to validate URLs
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]: can remove this

File: dashboard/src/pages/MyProfile.vue [hunk 3]
```diff
@@ -280,11 +280,42 @@ const toggleProfilePrivacy = () => {
...
   const errors = []
-  if (!profile_dict.full_name.trim()) errors.push('Full Name is required')
-  if (!profile_dict.username.trim()) errors.push('Username is required')
-  if (!profile_dict.user.trim()) errors.push('Email is required')
+  if (!profile_dict.full_name.trim()) errors.push('\nFull Name is required')
+  if (!profile_dict.username.trim()) errors.push('\nUsername is required')
+  if (!profile_dict.user.trim()) errors.push('\nEmail is required')
+
+  // This is jank as hell but its better than having a massive if-elif block
+  // I would have preferred to put all the links in a nested object named socials inside profile_dict itself, but that would break previously existing profiles.
```
Comment (harshtandiya) [inline dashboard/src/pages/MyProfile.vue]: let's get this removed. You can always specify this in PR descriptions, no need to set it in code

**Review by harshtandiya — APPROVED** [review]
