### PR TITLE
fix: make list of campaigns visible by def

### LINKED ISSUE #936: List of campaigns is only visible after a new campaign is created in same session
In the mailing section of an event, you cannot see the list of pre-existing campaigns until you create a new campaign.

Even then, if you refresh the page, the list of pre-existing campaigns stops being visible again.

https://github.com/user-attachments/assets/7bf33925-2789-4e28-8525-2ef54c65c983

### PR DESCRIPTION
**Pull request by gi-yt**
closes #936

### CODE REVIEW

File: dashboard/src/pages/mailing/EventMailing.vue [hunk 1]
```diff
@@ -69,11 +69,17 @@ const event = createDocumentResource({
...
 
+watch(
+  () => event.doc,
+  (doc) => {
+    if (doc) {
+      campaigns.fetch()
+    }
+  },
+)
+
```
Comment (harshtandiya) [inline dashboard/src/pages/mailing/EventMailing.vue]: Let's make this explicitly deep and immediate:

```js
watch(
  () => event.doc,
  (doc) => {
    if (doc) {
      campaigns.fetch()
    }
  },
 { 
    deep: true,
    immediate: true
 }
)
```

**Review by harshtandiya — APPROVED** [review]
