### PR TITLE
fix(hackathons): filters not working in localhost dashboard

### LINKED ISSUE #475: [BUG] Hackathons - Filters for requests aren't working in localhost dashboard
### Describe the bug

While changing status for requests in the filters of localhost dashbaord, the view isn't updated. 

On a refresh, it goes back to all requests. 
Screenshot 2024-07-17 at 12 40 36 PM

Add-on: The numbers of pending requests aren't updated too. 

Browser: Chrome, Arc

### PR DESCRIPTION
**Pull request by RiyaMathew-11**
## What type of PR is this? (check all applicable)
- [x] 🐛Bug Fix

## Description

- [x] Fixed the condition for filters not working in localhost organiser dashboard. Same implementation as #480
- [x] Fixed attendee detail dialog opening while clicking on action buttons.
    - Used `event.stopPropagation`

## Related Issues & Docs

- Closes #475 

## Checklist
- [x] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [x] I have tested these changes locally.
- [x] I have updated the documentation (If applicable).
- [x] ~The code follows the project's coding standards.~
- [x] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)

state-change-report

### CODE REVIEW

File: dashboard/src/components/localhost/AttendeeRequestList.vue [hunk 1]
```diff
@@ -225,35 +221,30 @@ const props = defineProps({
   },
 })
 
-const emit = defineEmits(['updateRequest'])
```
Comment (harshtandiya) [inline dashboard/src/components/localhost/AttendeeRequestList.vue:228]: Why remove this? this was a crucial fix to the bug which was not updating the status of requests in Localhost Dashboard page

File: dashboard/src/components/localhost/AttendeeRequestList.vue [hunk 2]
```diff
@@ -291,7 +282,6 @@ const changeLocalhostRequestStatus = (id, status) => {
     },
     onSuccess(data) {
       requestByGroup.fetch()
-      emit('updateRequest')
```
Comment (harshtandiya) [inline dashboard/src/components/localhost/AttendeeRequestList.vue]: Same here, this was related to the update stat bugfix 😅

File: dashboard/src/components/localhost/AttendeeRequestList.vue [hunk 3]
```diff
@@ -202,15 +198,15 @@
...
-import { defineProps } from 'vue'
+import { defineProps, watch } from 'vue'
 import {
   LoadingIndicator,
   createResource,
   Badge,
   Button,
   ListView,
 } from 'frappe-ui'
-import { ref, defineEmits } from 'vue'
```
Comment (harshtandiya) [inline dashboard/src/components/localhost/AttendeeRequestList.vue:213]: This is needed

File: dashboard/src/components/localhost/AttendeeRequestList.vue [hunk 4]
```diff
@@ -304,14 +294,14 @@ const rejectRequest = (member) => {
...
   requestByGroup.update({
     params: {
       hackathon: props.localhost.data.parent_hackathon,
       localhost: props.localhost.data.name,
-      status: filter.value,
+      status: FILTERS[newFilter].filters,
     },
   })
   requestByGroup.fetch()
-}
```
Comment (harshtandiya) [inline dashboard/src/components/localhost/AttendeeRequestList.vue:316]: Can you test and check the behavior on Firefox as well

**Review by harshtandiya — DISMISSED** [review]

File: dashboard/src/components/localhost/AttendeeRequestList.vue (hunk 4 above)
Comment (RiyaMathew-11) [reply dashboard/src/components/localhost/AttendeeRequestList.vue:316]: Yes did it too. I had tested in both browsers before pushing it. 

But if in this context, both are the same value, as is passed as a list too.

**Review by harshtandiya — APPROVED** [review]
