### PR TITLE
give chapter lead access to uncensored emails

### LINKED ISSUE #549: The chapter lead should have access to the emails of RSVPd candidates
### Describe the bug

This functionality was there earlier and removed in the new platform. We need the emails of the RSVPd candidates for further communication hence the chapter lead should definitely have access to the emails.  

Is there any specific reason this functionality was removed? If it's from a security perspective, then also chapter leads should have access to the data as we need this data for further communication and engagements.

### PR DESCRIPTION
**Pull request by gi-yt**
closes #549 
tested, confirmed to work

### CODE REVIEW

**Review by harshtandiya — COMMENTED** [review]
Maybe I was not clear in the previous PR, but we should really move away and use Frappe's inbuilt data export functions for this. That would allow custom questions to be exported as well.

**Comment by gi-yt** [comment]
This is not related to the export feature tho, I primarily changed this so that the lead can see RSVP emails on insights page

**Comment by gi-yt** [comment]
@harshtandiya can you move forward with this PR whenever possible, its a feature I'd personally like to have/use for  upcoming Mumbai meetup(s)

File: dashboard/src/pages/EventRsvpInsights.vue [hunk 1]
```diff
@@ -47,6 +49,21 @@ const rsvp_form = createResource({
   auto: true,
 })
 
+var isEventLead = false;
```
Comment (harshtandiya) [inline dashboard/src/pages/EventRsvpInsights.vue]: const isEventLead = ref(false)

File: fossunited/api/chapter.py [hunk 2]
```diff
@@ -33,3 +33,33 @@ def check_if_chapter_member(chapter: str, user: str) -> bool:
...
+                "email": user,
+                "parentfield": "event_members",
+            },
+            "role",
+        )
+        == "Lead"
+    ):
+        return True
+
+    return False
```
Comment (harshtandiya) [inline fossunited/api/chapter.py]: this can be done with frappe.db.exist
```py
user_profile = frappe.db.get_value(PROFILE, {"user": frappe.session.user}, ["name])

return bool( frappe.db.exists(
   "FOSS Chapter Event Member",
   {
      "parent": event,
      "parenttype": EVENT,
      "member": user_profile,
      "parentfield" : "event_members"
      "role": "Lead",
    },
))

```

File: fossunited/api/chapter.py [hunk 3]
```diff
@@ -33,3 +33,33 @@ def check_if_chapter_member(chapter: str, user: str) -> bool:
     )
 
     return is_member
+
+
+@frappe.whitelist(allow_guest=True)
+def check_if_event_lead(event: str, user: str) -> bool:
```
Comment (harshtandiya) [inline fossunited/api/chapter.py]: don't pass the user

File: dashboard/src/pages/EventRsvpInsights.vue [hunk 4]
```diff
@@ -47,6 +49,21 @@ const rsvp_form = createResource({
...
+const event_lead = createResource({
+  url: 'fossunited.api.chapter.check_if_event_lead',
+  makeParams() {
+    return {
+      event: route.params.id,
+      user: session.user,
```
Comment (harshtandiya) [inline dashboard/src/pages/EventRsvpInsights.vue]: let's not pass the user

File: dashboard/src/pages/EventRsvpInsights.vue [hunk 5]
```diff
@@ -47,6 +49,21 @@ const rsvp_form = createResource({
...
+    }
+  },
+  onSuccess(data) {
+    isEventLead = data
```
Comment (harshtandiya) [inline dashboard/src/pages/EventRsvpInsights.vue]: isEventLead.value = data

**Comment by gi-yt** [comment]
@harshtandiya is it good to merge now?

File: fossunited/api/chapter.py [hunk 6]
```diff
@@ -33,3 +33,34 @@ def check_if_chapter_member(chapter: str, user: str) -> bool:
...
+                "parenttype": EVENT,
+                "member": profile,
+                "parentfield": "event_members",
+                "role": "Lead",
+            },
+        )
+    ):
+        return True
+
+    return False
```
Comment (harshtandiya) [inline fossunited/api/chapter.py]: You dont need if blocks.

Refer to my earlier comment

**Comment by gi-yt** [comment]
is it good now @harshtandiya

**Review by harshtandiya — APPROVED** [review]
