### PR TITLE
bugfixes sprint #1

### LINKED ISSUE #316: [BUG] The footer seems to override the body on the `cfp/all` page (possibly others too)
### Describe the bug

Sample link: https://fossunited.org/events/blr-may/cfp/all

The tiles on the bottom seem to get hidden, probably due to the body not using its own content height. This issue can be potentially more general than for this page alone.

### Expected behavior

The footer should not hide the main body. Currently it works by zooming out (Cmd -)
image

### To Reproduce

1. Login and visit https://fossunited.org/events/blr-may/cfp/all
2. The issue should be visible. If not, try to set smaller device screen using the dev console

### Screenshots

image

### Environment

```markdown
- Device: Desktop
- OS: MacOS 14.4.11
- Browser: Google Chrome
```

### Additional context

_No response_

### LINKED ISSUE #320: Q: Order of "Scheduled Events" in the Dashboard page
### Issue description

The order of the "Scheduled Events" information in the [Dashboard page](https://fossunited.org/dashboard/) isn't obvious. It doesn't look like it's ordered reverse chronologically.

Screenshot 2024-05-15 080231

### Expected behavior

I expected the events to be ordered reverse chronologically, and then sorted into buckets that contain finished events vs unfinished events

### LINKED ISSUE #325: Publish Events on Creation
### Issue description

"Is Published" should be checked by default.

### PR DESCRIPTION
**Pull request by harshtandiya**
- closes #316 

Fixed styling issue by removing `h-100` class from the container div.
<hr>
- Cleaned up some orphaned files
<hr>
- closes #325
<br>
Status option now handles the published and unpublished state of the event. <br>
`Draft` & `Cancelled` status -> **Unpublished** <br>
`Live` & `Concluded` status -> **Published** <br>
<br>
Additionally, added a function which handles the permalink & route of event if the status has been changed to `Concluded`. The function adds `-archive-<hash>` at the end of permalink. 
<hr>
- closes #320 <br>
Fixed two issues: <br>
1. Order of events is based on `event_start_date` <br>
2. There was a bug which showed, any dashboard user, all the events for a split second. Fixed that so it doesn't happen in the future <br>

### CODE REVIEW

**Comment by RiyaMathew-11** [comment]
> - Cleaned up some orphaned files

I am guessing all the deleted files @harshtandiya ? Any modifications made in existing files as part of cleanup ?

File: dashboard/src/pages/Home.vue [hunk 1]
```diff
@@ -67,7 +67,7 @@ let scheduled_events = createListResource({
   filters: {
     status: ['in', ['', 'Draft', 'Approved', 'Live']],
   },
-  auto: true,
+  orderBy: 'event_start_date',
```
Comment (RiyaMathew-11) [inline dashboard/src/pages/Home.vue:70]: How would `order by start date` fetch events of member chapter, as the commit says that. A bit confused - am I missing something?

File: fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py [hunk 2]
```diff
@@ -104,8 +104,30 @@ def copy_team_members(self):
...
+        if self.has_value_changed("status"):
+            self.update_published_status()
         self.set_route()
 
+    def update_published_status(self):
+        if self.status == "Draft" or self.status == "Cancelled":
+            self.is_published = 0
+            return
+
+        if self.status == "Live" or self.status == "Approved":
```
Comment (RiyaMathew-11) [inline fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py:116]: Why `Approved` and `Live` together ? - We would only need `Live` or either one ?

File: fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py [hunk 3]
```diff
@@ -104,8 +104,30 @@ def copy_team_members(self):
...
+            self.is_published = 1
+            return
+
+        if self.status == "Concluded":
+            self.is_published = 1
+            self.handle_concluded_event()
+
+    def handle_concluded_event(self):
+        event_permalink = self.event_permalink
+        self.event_permalink = f"{event_permalink}-archive-{frappe.generate_hash(length=8)}"
```
Comment (RiyaMathew-11) [inline fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py:126]: What is this for ?

**Review by RiyaMathew-11 — CHANGES_REQUESTED** [review]

File: fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py (hunk 2 above)
Comment (harshtandiya) [reply fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py:116]: Because we have current events with Approved status. Will remove approved in future, it is here right now so that existing stuff do not break

File: dashboard/src/pages/Home.vue (hunk 1 above)
Comment (harshtandiya) [reply dashboard/src/pages/Home.vue:70]: `auto` line which is removed is the one that fixes the issue of all events being fetched. This resource is now fetched after the organisers's chapter data is loaded

File: fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py (hunk 3 above)
Comment (harshtandiya) [reply fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py:126]: as mentioned in the PR description, it is to help archive the events. Permalinks will be changed to end with `-archive-<hash>` which will free up the existing permalink that was being used.

File: fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py (hunk 2 above)
Comment (RiyaMathew-11) [reply fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.py:116]: Considering we have only 4 live events - is there a possibility we could manually changed it in the desk soon after deploy?

**Review by RiyaMathew-11 — APPROVED** [review]

**Comment by rahulporuri** [comment]
@harshtandiya can you tag the issues using "fixes" or "closes" or something along those lines? that way, as soon as this PR is merged, github will close the issues. see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

**Comment by harshtandiya** [comment]
Sure @rahulporuri
